services: 
  file-storage-minio:
    container_name: minio
    image: quay.io/minio/minio
    env_file: .env
    ports: 
      - "9000:9000"
      - "9001:9001"
    volumes: 
      - ./minio_data:/data
    command: >
       server /data --console-address ":9001"

  data-storage-postgres:
    container_name: data_storage_postgres
    image: postgres
    env_file: .env
    ports:
      - "9002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10
  
  app: 
    container_name: gophkeeper
    image: gopherkeeper:latest
    env_file: .env
    environment: 
      POSTGRES_HOST: data_storage_postgres
      MINIO_HOST: minio
    ports: 
      - "3200:3200"
    depends_on:
      data-storage-postgres:
        condition: service_healthy
networks: 
  default: 
    name: gopherkeeper-network
