// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JWTtoken      string                 `protobuf:"bytes,2,opt,name=JWTtoken,proto3" json:"JWTtoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Result) GetJWTtoken() string {
	if x != nil {
		return x.JWTtoken
	}
	return ""
}

type Verify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneTimePass   string                 `protobuf:"bytes,1,opt,name=oneTimePass,proto3" json:"oneTimePass,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify) Reset() {
	*x = Verify{}
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify) ProtoMessage() {}

func (x *Verify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify.ProtoReflect.Descriptor instead.
func (*Verify) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *Verify) GetOneTimePass() string {
	if x != nil {
		return x.OneTimePass
	}
	return ""
}

func (x *Verify) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type PasswordMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Application   string                 `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	MetaData      string                 `protobuf:"bytes,3,opt,name=metaData,proto3" json:"metaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordMessage) Reset() {
	*x = PasswordMessage{}
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordMessage) ProtoMessage() {}

func (x *PasswordMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordMessage.ProtoReflect.Descriptor instead.
func (*PasswordMessage) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordMessage) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *PasswordMessage) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

type FileMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MetaData      string                 `protobuf:"bytes,3,opt,name=metaData,proto3" json:"metaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMessage) Reset() {
	*x = FileMessage{}
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessage) ProtoMessage() {}

func (x *FileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessage.ProtoReflect.Descriptor instead.
func (*FileMessage) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *FileMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileMessage) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

type BankCardMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	CvcCode       string                 `protobuf:"bytes,2,opt,name=cvcCode,proto3" json:"cvcCode,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Bank          string                 `protobuf:"bytes,4,opt,name=bank,proto3" json:"bank,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardMessage) Reset() {
	*x = BankCardMessage{}
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardMessage) ProtoMessage() {}

func (x *BankCardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardMessage.ProtoReflect.Descriptor instead.
func (*BankCardMessage) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *BankCardMessage) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *BankCardMessage) GetCvcCode() string {
	if x != nil {
		return x.CvcCode
	}
	return ""
}

func (x *BankCardMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BankCardMessage) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *BankCardMessage) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type SensetiveDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identificator string                 `protobuf:"bytes,1,opt,name=identificator,proto3" json:"identificator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensetiveDataMessage) Reset() {
	*x = SensetiveDataMessage{}
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensetiveDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensetiveDataMessage) ProtoMessage() {}

func (x *SensetiveDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensetiveDataMessage.ProtoReflect.Descriptor instead.
func (*SensetiveDataMessage) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *SensetiveDataMessage) GetIdentificator() string {
	if x != nil {
		return x.Identificator
	}
	return ""
}

type DataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passwords     []*PasswordMessage     `protobuf:"bytes,1,rep,name=passwords,proto3" json:"passwords,omitempty"`
	BankCards     []*BankCardMessage     `protobuf:"bytes,2,rep,name=bankCards,proto3" json:"bankCards,omitempty"`
	Files         []*FileMessage         `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *DataMessage) GetPasswords() []*PasswordMessage {
	if x != nil {
		return x.Passwords
	}
	return nil
}

func (x *DataMessage) GetBankCards() []*BankCardMessage {
	if x != nil {
		return x.BankCards
	}
	return nil
}

func (x *DataMessage) GetFiles() []*FileMessage {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gophkeeper.proto\x12)github.com.Tanya1515.gophkeeper.git.proto\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"<\n" +
	"\x06Result\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bJWTtoken\x18\x02 \x01(\tR\bJWTtoken\"@\n" +
	"\x06Verify\x12 \n" +
	"\voneTimePass\x18\x01 \x01(\tR\voneTimePass\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\"k\n" +
	"\x0fPasswordMessage\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12 \n" +
	"\vapplication\x18\x02 \x01(\tR\vapplication\x12\x1a\n" +
	"\bmetaData\x18\x03 \x01(\tR\bmetaData\"_\n" +
	"\vFileMessage\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1a\n" +
	"\bmetaData\x18\x03 \x01(\tR\bmetaData\"\x8f\x01\n" +
	"\x0fBankCardMessage\x12\x1e\n" +
	"\n" +
	"cardNumber\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x18\n" +
	"\acvcCode\x18\x02 \x01(\tR\acvcCode\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04bank\x18\x04 \x01(\tR\x04bank\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"<\n" +
	"\x14SensetiveDataMessage\x12$\n" +
	"\ridentificator\x18\x01 \x01(\tR\ridentificator\"\x8f\x02\n" +
	"\vDataMessage\x12X\n" +
	"\tpasswords\x18\x01 \x03(\v2:.github.com.Tanya1515.gophkeeper.git.proto.PasswordMessageR\tpasswords\x12X\n" +
	"\tbankCards\x18\x02 \x03(\v2:.github.com.Tanya1515.gophkeeper.git.proto.BankCardMessageR\tbankCards\x12L\n" +
	"\x05files\x18\x03 \x03(\v26.github.com.Tanya1515.gophkeeper.git.proto.FileMessageR\x05files2\xc7\v\n" +
	"\n" +
	"Gophkeeper\x12V\n" +
	"\tLoginUser\x12/.github.com.Tanya1515.gophkeeper.git.proto.User\x1a\x16.google.protobuf.Empty\"\x00\x12Y\n" +
	"\fRegisterUser\x12/.github.com.Tanya1515.gophkeeper.git.proto.User\x1a\x16.google.protobuf.Empty\"\x00\x12{\n" +
	"\x13VerificationApprove\x121.github.com.Tanya1515.gophkeeper.git.proto.Verify\x1a1.github.com.Tanya1515.gophkeeper.git.proto.Result\x12f\n" +
	"\x0eUploadPassword\x12:.github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x0eUploadBankCard\x12:.github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage\x1a\x16.google.protobuf.Empty\"\x00\x12`\n" +
	"\n" +
	"UploadFile\x126.github.com.Tanya1515.gophkeeper.git.proto.FileMessage\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12k\n" +
	"\x0eDeletePassword\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\n" +
	"DeleteFile\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a\x16.google.protobuf.Empty\"\x00\x12v\n" +
	"\x19DeleteBankCardCredentials\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\x8a\x01\n" +
	"\vGetPassword\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a:.github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage\x12\x95\x01\n" +
	"\x16GetBankCardCredentials\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a:.github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage\x12\x84\x01\n" +
	"\aGetFile\x12?.github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage\x1a6.github.com.Tanya1515.gophkeeper.git.proto.FileMessage0\x01\x12]\n" +
	"\vGetInfoData\x12\x16.google.protobuf.Empty\x1a6.github.com.Tanya1515.gophkeeper.git.proto.DataMessageB\vZ\tcmd/protob\x06proto3"

var (
	file_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_proto_rawDescData []byte
)

func file_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)))
	})
	return file_proto_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_gophkeeper_proto_goTypes = []any{
	(*User)(nil),                 // 0: github.com.Tanya1515.gophkeeper.git.proto.User
	(*Result)(nil),               // 1: github.com.Tanya1515.gophkeeper.git.proto.Result
	(*Verify)(nil),               // 2: github.com.Tanya1515.gophkeeper.git.proto.Verify
	(*PasswordMessage)(nil),      // 3: github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage
	(*FileMessage)(nil),          // 4: github.com.Tanya1515.gophkeeper.git.proto.FileMessage
	(*BankCardMessage)(nil),      // 5: github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage
	(*SensetiveDataMessage)(nil), // 6: github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	(*DataMessage)(nil),          // 7: github.com.Tanya1515.gophkeeper.git.proto.DataMessage
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	3,  // 0: github.com.Tanya1515.gophkeeper.git.proto.DataMessage.passwords:type_name -> github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage
	5,  // 1: github.com.Tanya1515.gophkeeper.git.proto.DataMessage.bankCards:type_name -> github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage
	4,  // 2: github.com.Tanya1515.gophkeeper.git.proto.DataMessage.files:type_name -> github.com.Tanya1515.gophkeeper.git.proto.FileMessage
	0,  // 3: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.LoginUser:input_type -> github.com.Tanya1515.gophkeeper.git.proto.User
	0,  // 4: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.RegisterUser:input_type -> github.com.Tanya1515.gophkeeper.git.proto.User
	2,  // 5: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.VerificationApprove:input_type -> github.com.Tanya1515.gophkeeper.git.proto.Verify
	3,  // 6: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadPassword:input_type -> github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage
	5,  // 7: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadBankCard:input_type -> github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage
	4,  // 8: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadFile:input_type -> github.com.Tanya1515.gophkeeper.git.proto.FileMessage
	6,  // 9: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeletePassword:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	6,  // 10: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeleteFile:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	6,  // 11: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeleteBankCardCredentials:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	6,  // 12: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetPassword:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	6,  // 13: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetBankCardCredentials:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	6,  // 14: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetFile:input_type -> github.com.Tanya1515.gophkeeper.git.proto.SensetiveDataMessage
	8,  // 15: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetInfoData:input_type -> google.protobuf.Empty
	8,  // 16: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.LoginUser:output_type -> google.protobuf.Empty
	8,  // 17: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.RegisterUser:output_type -> google.protobuf.Empty
	1,  // 18: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.VerificationApprove:output_type -> github.com.Tanya1515.gophkeeper.git.proto.Result
	8,  // 19: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadPassword:output_type -> google.protobuf.Empty
	8,  // 20: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadBankCard:output_type -> google.protobuf.Empty
	8,  // 21: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.UploadFile:output_type -> google.protobuf.Empty
	8,  // 22: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeletePassword:output_type -> google.protobuf.Empty
	8,  // 23: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeleteFile:output_type -> google.protobuf.Empty
	8,  // 24: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.DeleteBankCardCredentials:output_type -> google.protobuf.Empty
	3,  // 25: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetPassword:output_type -> github.com.Tanya1515.gophkeeper.git.proto.PasswordMessage
	5,  // 26: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetBankCardCredentials:output_type -> github.com.Tanya1515.gophkeeper.git.proto.BankCardMessage
	4,  // 27: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetFile:output_type -> github.com.Tanya1515.gophkeeper.git.proto.FileMessage
	7,  // 28: github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper.GetInfoData:output_type -> github.com.Tanya1515.gophkeeper.git.proto.DataMessage
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
