// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/gophkeeper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gophkeeper_LoginUser_FullMethodName                 = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/LoginUser"
	Gophkeeper_RegisterUser_FullMethodName              = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/RegisterUser"
	Gophkeeper_VerificationApprove_FullMethodName       = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/VerificationApprove"
	Gophkeeper_UploadPassword_FullMethodName            = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/UploadPassword"
	Gophkeeper_UploadBankCard_FullMethodName            = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/UploadBankCard"
	Gophkeeper_UploadFile_FullMethodName                = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/UploadFile"
	Gophkeeper_DeletePassword_FullMethodName            = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/DeletePassword"
	Gophkeeper_DeleteFile_FullMethodName                = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/DeleteFile"
	Gophkeeper_DeleteBankCardCredentials_FullMethodName = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/DeleteBankCardCredentials"
	Gophkeeper_GetPassword_FullMethodName               = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/GetPassword"
	Gophkeeper_GetBankCardCredentials_FullMethodName    = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/GetBankCardCredentials"
	Gophkeeper_GetFile_FullMethodName                   = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/GetFile"
	Gophkeeper_GetInfoData_FullMethodName               = "/github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper/GetInfoData"
)

// GophkeeperClient is the client API for Gophkeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophkeeperClient interface {
	LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error)
	VerificationApprove(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Result, error)
	UploadPassword(ctx context.Context, in *PasswordMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UploadBankCard(ctx context.Context, in *BankCardMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileMessage, emptypb.Empty], error)
	DeletePassword(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteFile(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteBankCardCredentials(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPassword(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*PasswordMessage, error)
	GetBankCardCredentials(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*BankCardMessage, error)
	GetFile(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileMessage], error)
	GetInfoData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DataMessage, error)
}

type gophkeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGophkeeperClient(cc grpc.ClientConnInterface) GophkeeperClient {
	return &gophkeeperClient{cc}
}

func (c *gophkeeperClient) LoginUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) VerificationApprove(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Gophkeeper_VerificationApprove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) UploadPassword(ctx context.Context, in *PasswordMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_UploadPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) UploadBankCard(ctx context.Context, in *BankCardMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_UploadBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileMessage, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gophkeeper_ServiceDesc.Streams[0], Gophkeeper_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileMessage, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gophkeeper_UploadFileClient = grpc.ClientStreamingClient[FileMessage, emptypb.Empty]

func (c *gophkeeperClient) DeletePassword(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_DeletePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) DeleteFile(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) DeleteBankCardCredentials(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gophkeeper_DeleteBankCardCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) GetPassword(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*PasswordMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordMessage)
	err := c.cc.Invoke(ctx, Gophkeeper_GetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) GetBankCardCredentials(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (*BankCardMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankCardMessage)
	err := c.cc.Invoke(ctx, Gophkeeper_GetBankCardCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophkeeperClient) GetFile(ctx context.Context, in *SensetiveDataMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gophkeeper_ServiceDesc.Streams[1], Gophkeeper_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensetiveDataMessage, FileMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gophkeeper_GetFileClient = grpc.ServerStreamingClient[FileMessage]

func (c *gophkeeperClient) GetInfoData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DataMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataMessage)
	err := c.cc.Invoke(ctx, Gophkeeper_GetInfoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophkeeperServer is the server API for Gophkeeper service.
// All implementations must embed UnimplementedGophkeeperServer
// for forward compatibility.
type GophkeeperServer interface {
	LoginUser(context.Context, *User) (*emptypb.Empty, error)
	RegisterUser(context.Context, *User) (*emptypb.Empty, error)
	VerificationApprove(context.Context, *Verify) (*Result, error)
	UploadPassword(context.Context, *PasswordMessage) (*emptypb.Empty, error)
	UploadBankCard(context.Context, *BankCardMessage) (*emptypb.Empty, error)
	UploadFile(grpc.ClientStreamingServer[FileMessage, emptypb.Empty]) error
	DeletePassword(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error)
	DeleteFile(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error)
	DeleteBankCardCredentials(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error)
	GetPassword(context.Context, *SensetiveDataMessage) (*PasswordMessage, error)
	GetBankCardCredentials(context.Context, *SensetiveDataMessage) (*BankCardMessage, error)
	GetFile(*SensetiveDataMessage, grpc.ServerStreamingServer[FileMessage]) error
	GetInfoData(context.Context, *emptypb.Empty) (*DataMessage, error)
	mustEmbedUnimplementedGophkeeperServer()
}

// UnimplementedGophkeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGophkeeperServer struct{}

func (UnimplementedGophkeeperServer) LoginUser(context.Context, *User) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedGophkeeperServer) RegisterUser(context.Context, *User) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedGophkeeperServer) VerificationApprove(context.Context, *Verify) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationApprove not implemented")
}
func (UnimplementedGophkeeperServer) UploadPassword(context.Context, *PasswordMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPassword not implemented")
}
func (UnimplementedGophkeeperServer) UploadBankCard(context.Context, *BankCardMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBankCard not implemented")
}
func (UnimplementedGophkeeperServer) UploadFile(grpc.ClientStreamingServer[FileMessage, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGophkeeperServer) DeletePassword(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassword not implemented")
}
func (UnimplementedGophkeeperServer) DeleteFile(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedGophkeeperServer) DeleteBankCardCredentials(context.Context, *SensetiveDataMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBankCardCredentials not implemented")
}
func (UnimplementedGophkeeperServer) GetPassword(context.Context, *SensetiveDataMessage) (*PasswordMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassword not implemented")
}
func (UnimplementedGophkeeperServer) GetBankCardCredentials(context.Context, *SensetiveDataMessage) (*BankCardMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankCardCredentials not implemented")
}
func (UnimplementedGophkeeperServer) GetFile(*SensetiveDataMessage, grpc.ServerStreamingServer[FileMessage]) error {
	return status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedGophkeeperServer) GetInfoData(context.Context, *emptypb.Empty) (*DataMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoData not implemented")
}
func (UnimplementedGophkeeperServer) mustEmbedUnimplementedGophkeeperServer() {}
func (UnimplementedGophkeeperServer) testEmbeddedByValue()                    {}

// UnsafeGophkeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophkeeperServer will
// result in compilation errors.
type UnsafeGophkeeperServer interface {
	mustEmbedUnimplementedGophkeeperServer()
}

func RegisterGophkeeperServer(s grpc.ServiceRegistrar, srv GophkeeperServer) {
	// If the following call pancis, it indicates UnimplementedGophkeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gophkeeper_ServiceDesc, srv)
}

func _Gophkeeper_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).LoginUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).RegisterUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_VerificationApprove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Verify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).VerificationApprove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_VerificationApprove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).VerificationApprove(ctx, req.(*Verify))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_UploadPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).UploadPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_UploadPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).UploadPassword(ctx, req.(*PasswordMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_UploadBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankCardMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).UploadBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_UploadBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).UploadBankCard(ctx, req.(*BankCardMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophkeeperServer).UploadFile(&grpc.GenericServerStream[FileMessage, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gophkeeper_UploadFileServer = grpc.ClientStreamingServer[FileMessage, emptypb.Empty]

func _Gophkeeper_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensetiveDataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_DeletePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).DeletePassword(ctx, req.(*SensetiveDataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensetiveDataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).DeleteFile(ctx, req.(*SensetiveDataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_DeleteBankCardCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensetiveDataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).DeleteBankCardCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_DeleteBankCardCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).DeleteBankCardCredentials(ctx, req.(*SensetiveDataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_GetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensetiveDataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).GetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_GetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).GetPassword(ctx, req.(*SensetiveDataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_GetBankCardCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensetiveDataMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).GetBankCardCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_GetBankCardCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).GetBankCardCredentials(ctx, req.(*SensetiveDataMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gophkeeper_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SensetiveDataMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GophkeeperServer).GetFile(m, &grpc.GenericServerStream[SensetiveDataMessage, FileMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gophkeeper_GetFileServer = grpc.ServerStreamingServer[FileMessage]

func _Gophkeeper_GetInfoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophkeeperServer).GetInfoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gophkeeper_GetInfoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophkeeperServer).GetInfoData(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Gophkeeper_ServiceDesc is the grpc.ServiceDesc for Gophkeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gophkeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.Tanya1515.gophkeeper.git.proto.Gophkeeper",
	HandlerType: (*GophkeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Gophkeeper_LoginUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Gophkeeper_RegisterUser_Handler,
		},
		{
			MethodName: "VerificationApprove",
			Handler:    _Gophkeeper_VerificationApprove_Handler,
		},
		{
			MethodName: "UploadPassword",
			Handler:    _Gophkeeper_UploadPassword_Handler,
		},
		{
			MethodName: "UploadBankCard",
			Handler:    _Gophkeeper_UploadBankCard_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _Gophkeeper_DeletePassword_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _Gophkeeper_DeleteFile_Handler,
		},
		{
			MethodName: "DeleteBankCardCredentials",
			Handler:    _Gophkeeper_DeleteBankCardCredentials_Handler,
		},
		{
			MethodName: "GetPassword",
			Handler:    _Gophkeeper_GetPassword_Handler,
		},
		{
			MethodName: "GetBankCardCredentials",
			Handler:    _Gophkeeper_GetBankCardCredentials_Handler,
		},
		{
			MethodName: "GetInfoData",
			Handler:    _Gophkeeper_GetInfoData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _Gophkeeper_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _Gophkeeper_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gophkeeper.proto",
}
